### ISSUE TITLE
return streamAdapter along with sinks, sources, run

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/base#7]
https://github.com/cyclejs/base/blob/master/src/index.ts#L179

return `streamAdapter` along with `sinks, sources, run`, this might be needed if for some libs may not know about origin of passed `Cycle` running function.

**Comment by staltz** [comment]
Can you give an example?

**Comment by whitecolor** [comment]
Kind of hypothetical example:

```js
const runAndAnalizeSinks = (Cycle, dataflow, drivers) => {
  const {sinks, sources, streamAdapter} = Cycle(dataflow, drivers)
  for (let key in sinks){
    streamAdapter.streamSubscribe(sinks[key], {
       ...
    })
  }
}
```

This could be used for example for some stream agnositc test framework or something like this. I'm currently working on this kind of framework, I faced this need, but it currently my design allows not to have this available (as I use `runSA` passed to driver), but it still may be needed in some cases hypothetically, so I propose to consider it.
